<?php

function trips_install() {
	node_types_rebuild();
	$types = node_type_get_types();
	node_add_body_field($types['trips']);
}


function trips_uninstall() {
	$sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
	$result = db_query($sql, array(':type' => 'trips'));
	$nids = array();
	foreach ($result as $row) {
		$nids[] = $row->nid;
	}
	// Delete all the nodes at once
	node_delete_multiple($nids);
	
	_node_types_build(TRUE);
	node_type_delete('trips');
	field_purge_batch(1000);
}
