<?php

function touristic_resources_node_info() {
	return array(
		'touristic_resources' => array(
			'name' => t('Touristic Resource'),
			'base' => 'touristic_resources',
			'description' => t('Use this content type to create a touristic resource.'),
			'has_title' => FALSE,
			'title_label' => t('Touristic Resource Title'),
		),
	);
}


function touristic_resources_menu_alter(&$callbacks) {
	if (!user_access('administer nodes')) {
		$callbacks['node/add/touristic_resources']['access callback'] = 'user_access';
		$callbacks['node/add/touristic_resources']['access arguments'] = array('administer nodes');
	}
}


function touristic_resources_permission() {
	return array(
		'create touristic resources' => array(
			'title' => t('Create a touristic resource'),
			'description' => t('Create a touristic resource'),
		),
		'edit own touristic resources' => array(
			'title' => t('Edit own touristic resource'),
			'description' => t('Edit your own touristic resource'),
		),
		'edit any touristic resources' => array(
			'title' => t('Edit any touristic resource'),
			'description' => t('Edit any touristic resource'),
		),
		'delete own touristic resources' => array(
			'title' => t('Delete own touristic resource'),
			'description' => t('Delete own touristic resource'),
		),
		'delete any touristic resources' => array(
			'title' => t('Delete any touristic resource'),
			'description' => t('Delete any touristic resource'),
		),
	);
}


function touristic_resources_node_access($node, $op, $account) {
	
	if (! is_object($node)) {
	    return NODE_ACCESS_IGNORE;
	}
	
	$is_author = $account->uid == $node->uid;
	switch ($op) {
		case 'create':
			if (user_access('create touristic resources', $account)) {
				return NODE_ACCESS_ALLOW;
			}
		case 'update':
			if (user_access('edit own touristic resources', $account) && $is_author || user_access('edit any touristic resources', $account)) {
				return NODE_ACCESS_ALLOW;
			}
		case 'delete':
			if (user_access('delete own touristic resources', $account) && $is_author || user_access('delete any touristic resources', $account)) {
				return NODE_ACCESS_ALLOW;
			}
	}
}



function touristic_resources_form($node, &$form_state) {
	
	drupal_add_css(drupal_get_path('module', 'touristic_resources') . '/touristic_resources.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
	
	
	if(!empty($node->title) && !empty($node->nid)){
		$result = db_query('SELECT id, resource_id, language_id, "name", brief_description, details, created_on, updated_on FROM wptsc_resource_infos WHERE resource_id='.$node->nid);
		$rtv_name=$node->title;
		foreach ($result as $row) {
			$rtv_brief_description=$row->brief_description;
			$rtv_details=$row->details;
			$rtv_resource_id=$row->resource_id;
			break;
		}
		
		$result = db_query('SELECT id, parent_id, count_likes, "type" FROM wptsc_resources WHERE id='.$rtv_resource_id);
		
		foreach ($result as $row) {
			$rtv_type=$row->type;
			break;
		}
		
		if($rtv_type==1){
			$result = db_query('SELECT address, email, site, phone, x("location"), y("location") FROM wptsc_pois WHERE resource_ptr_id='.$rtv_resource_id);
			foreach ($result as $row) {
				$rtv_address=$row->address;
				$rtv_email=$row->email;
				$rtv_site=$row->site;
				$rtv_phone=$row->phone;
				$rtv_location_x=$row->x;
				$rtv_location_y=$row->y;
				break;
			}	
		}else{
			$result = db_query('SELECT address, email, site, phone, service_type, x("location"), y("location") FROM wptsc_services WHERE resource_ptr_id='.$rtv_resource_id);
			foreach ($result as $row) {
				$rtv_address=$row->address;
				$rtv_email=$row->email;
				$rtv_site=$row->site;
				$rtv_phone=$row->phone;
				$rtv_service_type=$row->service_type;
				$rtv_location_x=$row->x;
				$rtv_location_y=$row->y;
				break;
			}
			
			switch($rtv_service_type){
				case 1: //accomodations
					$result = db_query('SELECT num_rooms, lower_price, higher_price FROM wptsc_accommodations WHERE service_ptr_id='.$rtv_resource_id);
					foreach ($result as $row) {
						$rtv_num_rooms=$row->num_rooms;
						$rtv_lower_price=$row->lower_price;
						$rtv_higher_price=$row->higher_price;
						break;
					}						
				break;
				case 2: //entertaniaments
					$result = db_query('SELECT schedule, price FROM wptsc_entertainments WHERE service_ptr_id='.$rtv_resource_id);
					foreach ($result as $row) {
						$rtv_schedule=$row->schedule;
						$rtv_price=$row->price;
						break;
					}
				break;
				case 3: //healths
					$result = db_query('SELECT schedule FROM wptsc_healths WHERE service_ptr_id='.$rtv_resource_id);
					foreach ($result as $row) {
						$rtv_hschedule=$row->schedule;
						break;
					}
				break;
				case 4: //restaurants
					$result = db_query('SELECT specialities, avg_meal_price FROM wptsc_restaurants WHERE service_ptr_id='.$rtv_resource_id);
					foreach ($result as $row) {
						$rtv_specialities=$row->specialities;
						$rtv_avg_meal_price=$row->avg_meal_price;
						break;
					}
				break;
			}
		}
	}
	
		
	$form['rt_name'] = array(
		'#title' => t('Name'),
		'#type' => 'textfield',
		'#required' => TRUE,
		'#default_value' => !empty($node->title) ? $node->title : '',
	);
	
	$form['rt_country'] = array(
		'#title' => t('Country'),
		'#type' => 'select',
		'#options' => country_get_list(),
	);
	
	$form['rt_country']['#attributes'] = array(
      'onchange' => 'codeAddress()'
    );
	
	$form['rt_city'] = array(
		'#title' => t('City'),
		'#type' => 'textfield',
		'#size' => 15,
	);
	
	$form['rt_city']['#attributes'] = array(
      	'onchange' => 'codeAddress()',
		'autocomplete' =>'off',
    );
	
	$form['rt_address'] = array(
		'#title' => t('Address'),
		'#type' => 'textfield',
		'#size' => 30,
	);
	
	$form['rt_address']['#attributes'] = array(
      	'onchange' => 'codeAddress()',
		'autocomplete' =>'off',
    );
	
	$form['rt_zipcode'] = array(
		'#title' => t('Zip Code'),
		'#type' => 'textfield',
		'#size' => 6,
	);
	
	
	$form['rt_zipcode']['#attributes'] = array(
      	'onchange' => 'codeAddress()',
		'autocomplete' =>'off',
    );
	
	$form['blinky'] = array(
		'#markup' => '
			<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
			<script type="text/javascript">
			  	window.onload = function() {
				  	initialize();
				}
			</script>
			<div align="center"><div id="map_canvas" style="width: 550px; height: 400px"></div></div>		
		');
	
	
	$opc_category =  array(0 => t('-Select-'),1 => t('Points of Interest'), 2=> t('Services'));
		
	$form['rt_category'] = array(
		'#type' => 'select',
		'#title' => t('Category'),
		'#options' => $opc_category,
		'#required' => TRUE,
		'#default_value' => !empty($rtv_type) ? $rtv_type : 0,
	);
	
	$form['rt_services'] = array(
		'#title' => t('Description'),
		'#type' => 'fieldset',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
		'#states' => array(
				'visible' => array(
					':input[name="rt_category"]' => array('value' => 2),
		 	),
		 ),
	  );
	
	$form['rt_email'] = array(
		'#type' => 'textfield',
		'#title' => t('E-mail'),
		'#size' => 22,
		'#default_value' => !empty($rtv_email) ? $rtv_email : '',
	);
	
	$form['rt_site'] = array(
		'#type' => 'textfield',
		'#title' => t('Site'),
		'#size' => 22,
		'#default_value' => !empty($rtv_site) ? $rtv_site : '',
	);
	
	$form['rt_phone'] = array(
		'#type' => 'textfield',
		'#title' => t('Phone'),
		'#size' => 15,
		'#default_value' => !empty($rtv_phone) ? $rtv_phone : '',
	);
	
	
	$form['rt_services']['rt_subcategory'] = array(
		'#title' => t('SubCategory'),
		'#type' => 'select',
		'#options' => array(0 => t('-Select-'), 1 => t('Acommodations'), 2 => t('Entertainments'), 3 => t('Healths'), 4 => t('Restaurants')),
		'#default_value' => !empty($rtv_service_type) ? $rtv_service_type : 0,
		'#ajax' => array(
			'callback' => 'rt_services_ajax1',
			'wrapper' => 'rt_services_div',
		)	
	);
	
	$form['rt_services']['rt_services_description'] = array(
		'#type' => 'markup',
		'#prefix' => '<div id="rt_services_div">',
		'#suffix' => '</div>',
	  );
	
	if(!empty($rtv_service_type) && !isset($form_state['values']['rt_subcategory'])) $form_state['values']['rt_subcategory']=$rtv_service_type;
	
	if (isset($form_state['values']['rt_subcategory'])) {
		
		$services_type = $form_state['values']['rt_subcategory'];
		
		switch ($services_type) {
			case 1:
				  $form['rt_services']['rt_services_description']['rt_ente_num_rooms'] = array(
					'#type' => 'textfield',
					'#title' => t('Number of rooms'),
					'#size' => 15,
					'#default_value' => !empty($rtv_num_rooms) ? $rtv_num_rooms : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_num_rooms']['#attributes'] = array(
					  'onchange' => 'rt_ente_num_rooms_change()'
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_lower_price'] = array(
					'#type' => 'textfield',
					'#title' => t('Lower price'),
					'#size' => 15,
					'#default_value' => !empty($rtv_lower_price) ? $rtv_lower_price : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_lower_price']['#attributes'] = array(
					  'onchange' => 'rt_ente_lower_price_change()'
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_higher_price'] = array(
					'#type' => 'textfield',
					'#title' => t('Higher price'),
					'#size' => 15,
					'#default_value' => !empty($rtv_higher_price) ? $rtv_higher_price : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_higher_price']['#attributes'] = array(
					  'onchange' => 'rt_ente_higher_price_change()'
				  );
			break;
			
			case 2:
				  $form['rt_services']['rt_services_description']['rt_ente_schedule'] = array(
					'#type' => 'textfield',
					'#title' => t('Schedule'),
					'#size' => 30,
					'#default_value' => !empty($rtv_schedule) ? $rtv_schedule : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_schedule']['#attributes'] = array(
					  'onchange' => 'rt_ente_schedule_change()'
				  );
				  
				 $form['rt_services']['rt_services_description']['rt_ente_price'] = array(
					'#type' => 'textfield',
					'#title' => t('Price'),
					'#size' => 15,
					'#default_value' => !empty($rtv_price) ? $rtv_price : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_ente_price']['#attributes'] = array(
					  'onchange' => 'rt_ente_price_change()'
				  );
			break;
			
			case 3:
				$form['rt_services']['rt_services_description']['rt_heal_schedule'] = array(
					'#type' => 'textfield',
					'#title' => t('Schedule'),
					'#size' => 30,
					'#default_value' => !empty($rtv_hschedule) ? $rtv_hschedule : '',
				  );
				  
				  $form['rt_services']['rt_services_description']['rt_heal_schedule']['#attributes'] = array(
					  'onchange' => 'rt_ente_hschedule_change()'
				  );
		  
			break;
			case 4:
				$form['rt_services']['rt_services_description']['rt_rest_specialities'] = array(
					'#type' => 'textfield',
					'#title' => t('Specialities'),
					'#size' => 30,
					'#default_value' => !empty($rtv_specialities) ? $rtv_specialities : '',
				);
				
				$form['rt_services']['rt_services_description']['rt_rest_specialities']['#attributes'] = array(
					  'onchange' => 'rt_rest_specialities_change()'
				  );
				
				$form['rt_services']['rt_services_description']['rt_rest_avg_meal_price'] = array(
					'#type' => 'textfield',
					'#title' => t('Average Meal Price'),
					'#size' => 15,
					'#default_value' => !empty($rtv_avg_meal_price) ? $rtv_avg_meal_price : '',
				);
				
				$form['rt_services']['rt_services_description']['rt_rest_avg_meal_price']['#attributes'] = array(
					  'onchange' => 'rt_rest_avg_meal_price_change()'
				  );
	
			break;
		}
	}
	

	$form['rt_brief_description'] = array(
		'#type' => 'textarea',
		'#title' => t('Brief Description'),
		'#default_value' => !empty($rtv_brief_description) ? $rtv_brief_description : '',
	);
	
	$form['rt_details'] = array(
		'#type' => 'textarea',
		'#title' => t('Details'),
		'#default_value' => !empty($rtv_details) ? $rtv_details : '',
	);
	
	$form['rt_location_x'] = array(
		'#type' => 'textfield',
		'#size' => 40,
		'#default_value' => !empty($rtv_location_x) ? $rtv_location_x : '',
	);
	
	$form['rt_location_y'] = array(
		'#type' => 'textfield',
		'#size' => 40,
		'#default_value' => !empty($rtv_location_y) ? $rtv_location_y : '',
	);
	
	$form['rt_full_address'] = array(
		'#type' => 'textfield',
		'#size' => 36,
		'#default_value' => !empty($rtv_address) ? $rtv_address : '',
	);
	
	
	/*accommodations*/
	$form['rt_entex_num_rooms'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_num_rooms) ? $rtv_num_rooms : '',
	);
	
	$form['rt_entex_lower_price'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_lower_price) ? $rtv_lower_price : '',
	);
	
	$form['rt_entex_higher_price'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_higher_price) ? $rtv_higher_price : '',
	);
	
	/*enterteniaments*/
	$form['rt_entexx_schedule'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_schedule) ? $rtv_schedule : '',
	);
	
	$form['rt_entexx_price'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_price) ? $rtv_price : '',
	);	
		
	/*healths*/	
	$form['rt_healtx_schedule'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_hschedule) ? $rtv_hschedule : '',
	);
	
	/*restaurants*/
	$form['rt_restx_specialities'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_specialities) ? $rtv_specialities : '',
	);
	
	$form['rt_restx_avg_meal_price'] = array(
		'#type' => 'textfield',
		'#size' => 15,
		'#default_value' => !empty($rtv_avg_meal_price) ? $rtv_avg_meal_price : '',
	);
	
	return $form;
}



function rt_services_ajax1($form, &$form_state){
	return $form['rt_services']['rt_services_description'];
}


function touristic_resources_validate(&$node, $form, &$form_state) {
  ////////$node->title = $node->rt_name;
   
  if (!empty($form_state['values']['rt_ente_num_rooms']) && !is_numeric($form_state['values']['rt_ente_num_rooms'])) {
		form_set_error('rt_ente_num_rooms', t('Number rooms is not a number.'));
	}
	if (!empty($form_state['values']['rt_ente_lower_price']) && !is_numeric($form_state['values']['rt_ente_lower_price'])) {
		form_set_error('rt_ente_lower_price', t('Lower price is not a number.'));
	}
	if (!empty($form_state['values']['rt_ente_higher_price']) && !is_numeric($form_state['values']['rt_ente_higher_price'])) {
		form_set_error('rt_ente_higher_price', t('Higher price is not a number.'));
	}
	if (!empty($form_state['values']['rt_ente_price']) && !is_numeric($form_state['values']['rt_ente_price'])) {
		form_set_error('rt_ente_price', t('Price is not a number.'));
	}
}


/**
* Implements hook_insert().
*/
function touristic_resources_insert($node, $form_state) {

		
	$timestampa = date('Y-m-d G:i:s.BO');
  	
	$id_rt = $node->nid;
	$name_rt = $node->rt_name;
	$category_rt = $node->rt_category;
	$brief_description_rt = $node->rt_brief_description;
	$details_rt = $node->rt_details;
	
	$email_rt = $node->rt_email;
	$site_rt = $node->rt_site;
	$phone_rt = $node->rt_phone;
	
	$location_rt = '('.$node->rt_location_x.' '.$node->rt_location_y.')';
	$full_address_rt = $node->rt_full_address;
	

	db_query('INSERT INTO wptsc_resources (id, count_likes, count_dislikes, created_on, updated_on, type) VALUES (:arg1, :arg2, :arg3, :arg4, :arg5, :arg6)', array(':arg1' => $node->nid, ':arg2' => 0, ':arg3' => 0, ':arg4' => $timestampa, ':arg5' => $timestampa, ':arg6' => $category_rt));
	
	db_query('INSERT INTO wptsc_resource_infos(resource_id, language_id, "name", brief_description, details,created_on, updated_on) VALUES (:arg1, :arg2, :arg3, :arg4, :arg5, :arg6, :arg7)', array(':arg1' => $id_rt, ':arg2' => 'en', ':arg3' => $name_rt, ':arg4' => $brief_description_rt, ':arg5' => $details_rt, ':arg6' => $timestampa, ':arg7' => $timestampa));
	
	
	if($category_rt==1){
		db_query('INSERT INTO wptsc_pois(resource_ptr_id, address, email, site, phone, "location") VALUES ('.$id_rt.', \''.$full_address_rt.'\', \''.$email_rt.'\', \''.$site_rt.'\', \''.$phone_rt.'\', GeometryFromText(\'POINT'.$location_rt.'\',4326))');
	}elseif($category_rt==2){
		
		$subcategory_rt = $node->rt_subcategory;
		db_query('INSERT INTO wptsc_services(resource_ptr_id, address, email, site, phone, service_type, "location") VALUES ('.$id_rt.', \''.$full_address_rt.'\', \''.$email_rt.'\', \''.$site_rt.'\', \''.$phone_rt.'\', '.$subcategory_rt.'  ,GeometryFromText(\'POINT'.$location_rt.'\',4326))');
		
		switch($subcategory_rt){
			case 1:
				$ente_num_rooms_rt = !empty($node->rt_entex_num_rooms) ? $node->rt_entex_num_rooms : 0;
				$ente_lower_price_rt = !empty($node->rt_entex_lower_price) ? $node->rt_entex_lower_price : 0;
				$ente_higher_price_rt = !empty($node->rt_entex_higher_price) ? $node->rt_entex_higher_price : 0;
				db_query('INSERT INTO wptsc_accommodations(service_ptr_id, num_rooms, lower_price, higher_price) VALUES (:arg1, :arg2, :arg3, :arg4)', array(':arg1' => $id_rt, ':arg2' => $ente_num_rooms_rt, ':arg3' => $ente_lower_price_rt, ':arg4' => $ente_higher_price_rt));
			break;
			case 2:
				$ente_schedule_rt = $node->rt_entexx_schedule;
				$ente_price_rt = !empty($node->rt_entexx_price) ? $node->rt_entexx_price : 0;
				db_query('INSERT INTO wptsc_entertainments(service_ptr_id, schedule, price) VALUES (:arg1, :arg2, :arg3)', array(':arg1' => $id_rt, ':arg2' => $ente_schedule_rt, ':arg3' => $ente_price_rt));
			break; 
			case 3:
				$heal_schedule_rt = $node->rt_healtx_schedule;
				db_query('INSERT INTO wptsc_healths(service_ptr_id, schedule) VALUES (:arg1, :arg2)', array(':arg1' => $id_rt, ':arg2' => $heal_schedule_rt));
			break; 
			case 4:
				$rest_specialities_rt = $node->rt_restx_specialities;
				$rest_avg_meal_price_rt = !empty($node->rt_restx_avg_meal_price) ? $node->rt_restx_avg_meal_price : 0;
				db_query('INSERT INTO wptsc_restaurants(service_ptr_id, specialities, avg_meal_price) VALUES (:arg1, :arg2, :arg3)', array(':arg1' => $id_rt, ':arg2' => $rest_specialities_rt, ':arg3' => $rest_avg_meal_price_rt));
			break; 	
		}
		
	}
	
	//drupal_set_message(t('The touristic resource "%name" was added successfully', array('%name' => $node->title)));
		
	watchdog('touristic resource', 'A new touristic resource titled: '.$node->title.' was added by UID: '.$node->uid, $variables = array(),WATCHDOG_NOTICE, $link = 'node/'.$node->nid);
	
	
}



function touristic_resources_update($node) {	
	$timestampa = date('Y-m-d G:i:s.BO');
	
	$id_rt = $node->nid;
	$name_rt = $node->rt_name;
	$category_rt = $node->rt_category;
	$brief_description_rt = $node->rt_brief_description;
	$details_rt = $node->rt_details;
	
	$email_rt = $node->rt_email;
	$site_rt = $node->rt_site;
	$phone_rt = $node->rt_phone;
	
	$location_rt = '('.$node->rt_location_x.' '.$node->rt_location_y.')';
	$full_address_rt = $node->rt_full_address;
	
	
	db_update('wptsc_resources')
		->fields(array(
				'updated_on' => $timestampa,
				'type' => $category_rt,
			))
		->condition('id', $id_rt)
		->execute();
	
	
	db_update('wptsc_resource_infos')
		->fields(array(
				'name' => $name_rt,
				'brief_description' => $brief_description_rt,
				'details' => $details_rt,
				'updated_on' => $timestampa,
		))
		->condition('resource_id', $id_rt)
		->execute();

	
	if($category_rt==1){
		
		$result = db_query('SELECT * FROM wptsc_pois WHERE resource_ptr_id='.$id_rt);
		if($result->rowCount()>0){//the same type
			db_query('UPDATE wptsc_pois SET address=\''.$full_address_rt.'\', email=\''.$email_rt.'\', site=\''.$site_rt.'\', phone=\''.$phone_rt.'\', "location"=GeometryFromText(\'POINT'.$location_rt.'\',4326) WHERE resource_ptr_id='.$id_rt);
		}else{
			db_query('INSERT INTO wptsc_pois(resource_ptr_id, address, email, site, phone, "location") VALUES ('.$id_rt.', \''.$full_address_rt.'\', \''.$email_rt.'\', \''.$site_rt.'\', \''.$phone_rt.'\', GeometryFromText(\'POINT'.$location_rt.'\',4326))');
			
			db_delete('wptsc_accommodations')->condition('service_ptr_id', $id_rt)->execute();
			db_delete('wptsc_entertainments')->condition('service_ptr_id', $id_rt)->execute();
			db_delete('wptsc_healths')->condition('service_ptr_id', $id_rt)->execute();
			db_delete('wptsc_restaurants')->condition('service_ptr_id', $id_rt)->execute();
			
			db_delete('wptsc_services')->condition('resource_ptr_id', $id_rt)->execute();
		}
		
	}elseif($category_rt==2){
		
		$subcategory_rt = $node->rt_subcategory;
		$result = db_query('SELECT * FROM wptsc_services WHERE resource_ptr_id='.$id_rt);
		
		if($result->rowCount()>0){//the same type
			db_query('UPDATE wptsc_services SET address=\''.$full_address_rt.'\', email=\''.$email_rt.'\', site=\''.$site_rt.'\', phone=\''.$phone_rt.'\', service_type='.$subcategory_rt.', "location"=GeometryFromText(\'POINT'.$location_rt.'\',4326) WHERE resource_ptr_id='.$id_rt);
		}else{
			db_query('INSERT INTO wptsc_services(resource_ptr_id, address, email, site, phone, service_type, "location") VALUES ('.$id_rt.', \''.$full_address_rt.'\', \''.$email_rt.'\', \''.$site_rt.'\', \''.$phone_rt.'\', '.$subcategory_rt.'  ,GeometryFromText(\'POINT'.$location_rt.'\',4326))');
			db_delete('wptsc_pois')->condition('resource_ptr_id', $id_rt)->execute();
		}
		
		switch($subcategory_rt){
			case 1:
				$ente_num_rooms_rt = $node->rt_entex_num_rooms;
				$ente_lower_price_rt = $node->rt_entex_lower_price;
				$ente_higher_price_rt = $node->rt_entex_higher_price;

				$result = db_query('SELECT * FROM wptsc_accommodations WHERE service_ptr_id='.$id_rt);
				if($result->rowCount()>0){//the same type
					db_update('wptsc_accommodations')
						->fields(array(
								'num_rooms' => $ente_num_rooms_rt,
								'lower_price' => $ente_lower_price_rt,
								'higher_price' => $ente_higher_price_rt,
						))
						->condition('service_ptr_id', $id_rt)
						->execute();
				}else{
					db_query('INSERT INTO wptsc_accommodations(service_ptr_id, num_rooms, lower_price, higher_price) VALUES (:arg1, :arg2, :arg3, :arg4)', array(':arg1' => $id_rt, ':arg2' => $ente_num_rooms_rt, ':arg3' => $ente_lower_price_rt, ':arg4' => $ente_higher_price_rt));
					
					db_delete('wptsc_entertainments')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_healths')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_restaurants')->condition('service_ptr_id', $id_rt)->execute();
				}		
				break;
			case 2:
				$ente_schedule_rt = $node->rt_entexx_schedule;
				$ente_price_rt = $node->rt_entexx_price;
				
				$result = db_query('SELECT * FROM wptsc_entertainments WHERE service_ptr_id='.$id_rt);
				if($result->rowCount()>0){//the same type
					db_update('wptsc_entertainments')
						->fields(array(
								'schedule' => $ente_schedule_rt,
								'price' => $ente_price_rt,
						))
						->condition('service_ptr_id', $id_rt)
						->execute();
				}else{
					db_query('INSERT INTO wptsc_entertainments(service_ptr_id, schedule, price) VALUES (:arg1, :arg2, :arg3)', array(':arg1' => $id_rt, ':arg2' => $ente_schedule_rt, ':arg3' => $ente_price_rt));
										
					db_delete('wptsc_accommodations')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_healths')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_restaurants')->condition('service_ptr_id', $id_rt)->execute();
				}
				break;
			case 3:
				$heal_schedule_rt = $node->rt_healtx_schedule;

				$result = db_query('SELECT * FROM wptsc_healths WHERE service_ptr_id='.$id_rt);
				if($result->rowCount()>0){//the same type
					db_update('wptsc_healths')
						->fields(array(
								'schedule' => $heal_schedule_rt,
						))
						->condition('service_ptr_id', $id_rt)
						->execute();
				}else{
					db_query('INSERT INTO wptsc_healths(service_ptr_id, schedule) VALUES (:arg1, :arg2)', array(':arg1' => $id_rt, ':arg2' => $heal_schedule_rt));
					
					db_delete('wptsc_accommodations')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_entertainments')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_restaurants')->condition('service_ptr_id', $id_rt)->execute();
				}
				break;
			case 4:
				$rest_specialities_rt = $node->rt_restx_specialities;
				$rest_avg_meal_price_rt = $node->rt_restx_avg_meal_price;
				if(strlen($rest_avg_meal_price_rt)<1) $rest_avg_meal_price_rt=0;
								
				$result = db_query('SELECT * FROM wptsc_restaurants WHERE service_ptr_id='.$id_rt);
				if($result->rowCount()>0){//the same type
					db_update('wptsc_restaurants')
						->fields(array(
								'specialities' => $rest_specialities_rt,
								'avg_meal_price' => $rest_avg_meal_price_rt,
						))
						->condition('service_ptr_id', $id_rt)
						->execute();
				}else{
					db_query('INSERT INTO wptsc_restaurants(service_ptr_id, specialities, avg_meal_price) VALUES (:arg1, :arg2, :arg3)', array(':arg1' => $id_rt, ':arg2' => $rest_specialities_rt, ':arg3' => $rest_avg_meal_price_rt));
										
					db_delete('wptsc_accommodations')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_entertainments')->condition('service_ptr_id', $id_rt)->execute();
					db_delete('wptsc_healths')->condition('service_ptr_id', $id_rt)->execute();
				}
				break;
		}
	
	}
	
	
	//drupal_set_message(t('The touristic resource "%name" was updated successfully', array('%name' => $node->title)));
	
	watchdog('touristic resource', 'A touristic resource titled: '.$node->title.' was updated by UID: '.$node->uid, $variables = array(),WATCHDOG_NOTICE, $link = 'node/'.$node->nid);
}



function touristic_resources_delete($node) {
	// log details of the touristic resourceing to watchdog
	watchdog('touristic resource', 'A touristic resource titled: '.$node->title.' was deleted by UID: '.$node->uid, $variables = array(),WATCHDOG_NOTICE, $link = 'node/'.$node->nid);
}



function touristic_resources_view($node, $view_mode) {
	// Add and theme the sponsor so it appears when the touristic resource is displayed
	//drupal_set_message('<pre>'. check_plain(print_r($node, TRUE)) .'</pre>');
	
	$result = db_query('SELECT id, resource_id, language_id, "name", brief_description, details FROM wptsc_resource_infos WHERE resource_id='.$node->nid);
		
	foreach ($result as $row) {
		$rt_brief_description=$row->brief_description;
		$rt_details=$row->details;
		$rt_resource_id=$row->resource_id;
		break;
	}
		
	$result = db_query('SELECT id, parent_id, count_likes, "type" FROM wptsc_resources WHERE id='.$rt_resource_id);
	
	foreach ($result as $row) {
		$rt_type=$row->type;
		break;
	}
	
	if($rt_type==1){
		$rt_type="Point of interest";	
	}else{
		$rt_type="Service";
	}
	
		
	if ($view_mode == 'full') {
		$node->content['touristic_resource'] = array(
			'#markup' => theme('touristic_resource', array('rt_name' => $rt_type,'rt_brief_description' => $rt_brief_description, 'rt_details' => $rt_details)),
			'#weight' => 100,
		);
	}
	return $node;
}


function touristic_resources_theme() {
	return array(
		'touristic_resource' => array(
			'variables' => array('rt_name' => NULL, 'rt_brief_description' => NULL, 'rt_details' => NULL),
			'template' => 'touristic_resource',
		),
	);
}
